export const PARTNERS_DATA = [
  {
    id: 1,
    name: "Carbon",
    logo: "/images/projects/icons/carbon.svg",
    size: "large",
    positionClass: "absolute inset-x-0 -right-2 top-[8.375rem] mx-auto",
    sizeClass: "size-[19.5625rem]",
    iconSize: { width: 145, height: 131 },
    eventCameraPosition: 0,
  },
  {
    id: 2,
    name: "Nest",
    logo: "/images/projects/icons/nest.svg",
    size: "small",
    positionClass: "absolute top-0 left-[18.375rem]",
    sizeClass: "size-[8.75rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 1,
  },
  {
    id: 3,
    name: "Garbo",
    logo: "/images/projects/icons/garbo.svg",
    size: "small",
    positionClass: "absolute right-[15.25rem] top-[.9375rem]",
    sizeClass: "size-[8.75rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 2,
  },
  {
    id: 4,
    name: "Linus",
    logo: "/images/projects/icons/linus.svg",
    size: "small",
    positionClass: "absolute right-[8.5rem] top-[6.8125rem]",
    sizeClass: "size-[8.75rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 3,
  },
  {
    id: 5,
    name: "PortalFi",
    logo: "/images/projects/icons/portalfi.svg",
    size: "medium",
    positionClass: "absolute bottom-[12.625rem] right-[3.4375rem]",
    sizeClass: "size-[12.5rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 4,
  },
  {
    id: 6,
    name: "Sozialens",
    logo: "/images/projects/icons/sozialens.svg",
    size: "small",
    positionClass: "absolute right-[12.75rem] bottom-[6.5rem]",
    sizeClass: "size-[8.75rem]",
    iconSize: { width: 32, height: 32 },
    eventCameraPosition: 5,
  },
  {
    id: 7,
    name: "Accelera",
    logo: "/images/projects/icons/accelera.svg",
    size: "medium",
    positionClass: "absolute right-[21.1875rem] bottom-[.1875rem]",
    sizeClass: "size-[12.5rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 0,
  },
  {
    id: 8,
    name: "Lode",
    logo: "/images/projects/icons/lode.svg",
    size: "small",
    positionClass: "absolute left-[10.6875rem] bottom-[8.875rem]",
    sizeClass: "size-[8.75rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 1,
  },
  {
    id: 9,
    name: "Intenxt",
    logo: "/images/projects/icons/intenxt.svg",
    size: "medium",
    positionClass: "absolute bottom-[16.25rem] left-[3.4375rem]",
    sizeClass: "size-[12.5rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 2,
  },
  {
    id: 10,
    name: "Fenix",
    logo: "/images/projects/icons/fenix.svg",
    size: "small",
    positionClass: "absolute left-[10.6875rem] top-[4.4375rem]",
    sizeClass: "size-[8.75rem]",
    iconSize: { width: 60, height: 60 },
    eventCameraPosition: 3,
  },
];
